/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test public void rollTest() {
        // Arrange
        Library sut = new Library();
        // Act
        int numRolls = 10;
        int[] rolls = sut.roll(numRolls);

        // Assert that the length of the rolls array matches the number of rolls
        assertEquals(numRolls, rolls.length);

        // Assert that each roll value is within the valid range of 1 to 6
        for (int roll : rolls) {
            assertTrue(roll >= 1 && roll <= 6);
        }
    }

    @Test public void testContainsDuplicates() {
        Library sut = new Library();

        int[] array1 = {1, 2, 3, 4, 5};
        int[] array2 = {1, 2, 3, 3, 4};

        assertFalse(sut.containsDuplicates(array1)); // No duplicates, should return false
        assertTrue(sut.containsDuplicates(array2)); // Duplicates present, should return true
    }
}
