/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Arrays;
import java.util.Random;

public class Library {
    public static int[] roll(int n) {
        int[] rolls = new int[n];
        Random random = new Random();


        for (int i = 0; i < n; i++) {
            rolls[i] = random.nextInt(6) + 1;
        }
        return rolls;
    }
}
