/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Random;

public class Library {
    public static int[] roll(int n) {
        int[] rolls = new int[n];
        Random random = new Random();


        for (int i = 0; i < n; i++) {
            rolls[i] = random.nextInt(6) + 1;
        }
        return rolls;
    }

//
    public static boolean containsDuplicates(int[] rolls) {
        for (int i = 0; i < rolls.length - 1; i++) {
            for (int j = i + 1; j < rolls.length; j++) {
                if (rolls[i] == rolls[j]) {
                    return true; // Duplicate value found
                }
            }
        }

        return false; // No duplicate values found
    }
}
