/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;


import java.io.File;
import java.io.FileNotFoundException;
import java.nio.file.Path;
import java.util.Scanner;


public class App {
    public static void main(String[] args) {
        Path filePath = Path.of("C:\\Users\\rym54\\Projects\\code-401\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js");
        String errorMessages = validateJavaScriptFile(filePath.toFile());
        System.out.println(errorMessages);
    }

    public static String validateJavaScriptFile(File file) {
        StringBuilder errorMessage = new StringBuilder();

        try (Scanner scanner = new Scanner(file)) {
            int lineNum = 1;
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();

                if (line.trim().isEmpty()) {
                    // Skip empty lines
                    lineNum++;
                    continue;
                }

                String trimmedLine = line.trim();
                if (trimmedLine.endsWith("{") || trimmedLine.endsWith("}") || trimmedLine.contains("if") || trimmedLine.contains("else")) {
                    // Skip lines with opening or closing curly braces or containing 'if' or 'else'
                    lineNum++;
                    continue;
                }

                if (!trimmedLine.endsWith(";")) {
                    // Line missing a semicolon
                    errorMessage.append("Line ").append(lineNum).append(": Missing semicolon.").append(System.lineSeparator());
                }

                lineNum++;
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        return errorMessage.toString();
    }
}
