/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void testRestaurant() {
        Restaurant Test = new Restaurant("Applebees", 2,1);
        System.out.println(Test);
    }

    @Test void testReview() {
        Review Test = new Review("Rocio", "Good option for teenagers", 3);
        System.out.println(Test);
    }
}
